### ISSUE TITLE
feat: 添加 CSS font-family

### ISSUE THREAD

**Issue by KonghaYao** [KonghaYao/cn-font-split#8]
CSS 文件中完整的 src 属性应该包含 format 函数（参考自 [Learn Responsive Design - Typography](https://web.dev/learn/design/typography/)）。
```css
@font-face {
    font-family: "霞鹜文楷";
    font-weight: 400;
    src: local("LXGW WenKai"),
         url("./lxgwwenkai-regular-400.woff2") format("woff2"),
         url("./lxgwwenkai-regular-400.woff") format("woff"),
         url("./lxgwwenkai-regular-400.ttf") format("turetype"),
         url("./lxgwwenkai-regular-400.otf") format("opentype");
}
```
